name: Commitlint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      # -----------------------------------------------------------------------
      # Checkout repository
      # -----------------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false
          ssh-key: ${{ secrets.AI_DEPLOY_KEY }}
          ssh-strict: true

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v6
