name: Commitlint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          ssh-private-key: ${{ secrets.AI_DEPLOY_KEY }}

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v6
