name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flutter:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          ssh-private-key: ${{ secrets.AI_DEPLOY_KEY }}

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Check formatting
        run: flutter format --set-exit-if-changed .

      - name: Static analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test
